# Generated by Django 6.0.7 on 2026-07-18 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="collection",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.collection",
            ),
            preserve_default=False,
        ),
    ]
