# Generated by Django 6.0.7 on 2026-07-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_product_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inventory",
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
